name: Run Selenium + Behave Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies directly (no requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave selenium allure-behave allure-pytest pytest webdriver-manager requests

      # Step 4: Download Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          npm install -g allure-commandline --save-dev

      # Step 5: Run tests
      - name: Run Behave tests
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results -f pretty

      # Step 6: Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean

      # Step 7: Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/allure-report
          publish_branch: gh-pages
